// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swellvyvglqfwpnmlebs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3ZWxsdnl2Z2xxZndwbm1sZWJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3ODMzNzMsImV4cCI6MjA4NjM1OTM3M30.uOrKXa_uYJNsHau1aFNPOPuZGpzJ2V_cAiD4lnWs0lg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});